services:
  API:
    image: qyoga_back
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

  frontend:
    image: qyoga-front
    build:
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:3000
    ports:
      - "9090:80" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - API
    networks:
      - frontend

  # Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: