### Actuator discover
GET {{ servie }} /ops/actuator
Authorization: Basic admin@ta.pro password

### Actuator env
GET {{ servie }} /ops/actuator/env
Authorization: Basic admin@ta.pro password

### Actuator get logger info
GET {{ servie }} /ops/actuator/loggers/org.springframework.jdbc.core.JdbcTemplate
Authorization: Basic admin@ta.pro password


### Actuator set logger level
POST {{ servie }} /ops/actuator/loggers/org.springframework.jdbc.core.JdbcTemplate
Content-Type: application/json; charset=utf-8
Authorization: Basic admin@ta.pro password

{
  "configuredLevel": "INFO"
}