= Реализация страницы просмотра расписания списком

== Что вообще происходит

[WARNING]
====
Реализация отложена из-за недостаточной проработки аналитики.
====

Продолжаю пилить МВП расписаний.
Как-то так вышло, что при реализации создания приёма и до реализации его просмотра, не сделал привязку приёма к записи в журнале.
Пришло время это сделать.

== Что уже есть

Общая инфраструктура хранения приёмов и журнала, операция создания приёма.

=== Техдолг

. CreateAppointment не имеет суффикса Workflow
. Пакет журнала имеет устаревшую структуру
. Пакет журнала имеет устаревшую схему обработки ошибок:
.. Выброс исключения при удалении, если не найдено
.. Обёртка ошибки дублирования в кастомный тип
.. Возврат кастомного типа, в случае если не найден клиент при запросе страницы
. В редактировании записи не используется ErgoRepo.update

== Как это будет работать

=== UI/UX

=== Приёмы

Предположительно, без изменений

=== Журнал

==== Список

В карточке записи в нижнем блоки с кнопками добавится ссылка "Перейти к приёму".

==== Редактирование

На форме перед полем записи появится опциональный комбобокс?
Или селект?
Селект вроде тоже может быть многострочным

=== URLs

* Если будет комбобокс выбора приёма - /therapist/appointments/autocomplete-search

=== Операции системы

* Создание приёма - добавится вызов операции создания/привязки записи
* Запрос списка записей - добавится фетч приёма.
С типом...
* Запрос записи - добавится фетч приёма
* Обновление записи - добавится вызов обновления терапевтической задачи приёма

=== Операции ядра

* Journals.linkEntry(clientRef, localDate, appointmentRef) - находит запись по клиенту и дате, если нет - создаёт новую сущность, проставляет в сущности ссылку на приём и всё это сохраняет
* Appointments.updateBy(journalEntry) - находит приём по ссылке на него и обновляет

=== Модель

[source,kotlin]
----
data class JournalEntry(
    val appointmentRef: AppontmentRef?
)
----

=== Схема БД

[source,sql]
----
ALTER TABLE journal_entries
  ADD COLUMN appointment_ref BIGINT REFERENCES appointments;
----

== Тесты

=== Хеппи пасы

. Создание приёма
.. Если записи нет - она появляется
.. Если запись есть - проставляется ссылка
. Запрос списка записей
.. Если есть запись со ссылкой на приём - приём попадает в ответ
. Запрос записи
.. Сохранение максимально заполненной записи должно быть постоянным
. Обновление записи
.. Обновление максимально заполненной записи должно быть постоянным

=== Ошибки

. Создание приёма
.. Доменных ошибок вроде нет - запись всегда можно привязать
. Запрос списка записей
.. Чисто теоретический кейс отсутствия записи по ссылке обрабатывается на уровне гидрации
. Запрос записи
.. Чисто теоретический кейс отсутствия записи по ссылке обрабатывается на уровне гидрации
. Обновление записи
.. Доменных ошибок вроде нет

== Порядок выполнения

. Привести структуру модуля журнала к новому стандарту
. Добавить ссылку на приём и привязку записи журнала при создании приёма
. Добавить ссылку на приём в журнал
. Добавить инпут приёма но форму создания/редактирования записи