spring:

  flyway:
    locations: classpath:db/migration/common

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:54503/qyoga

  servlet:
    multipart:
      max-file-size: 10MB

  mail:
    username: qyogapro@yandex.ru
    password: <secret>
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        cachecontrol:
          max-age: 1h

management:
  endpoints:
    web:
      base-path: /ops/actuator

      exposure:
        include: configprops,loggers,env,info

  endpoint:
    configprops:
      show-values: when_authorized
      enabled: true
    env:
      enabled: true
      show-values: when_authorized

  info:
    git:
      mode: full
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

server:
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For

minio:
  user: user
  password: password
  endpoint: http://localhost:50000

trainer-advisor:
  admin:
    email: ta@azhidkov.pro

debug: false