spring:

  flyway:
    locations: classpath:db/migration/common

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:54503/qyoga

  servlet:
    multipart:
      max-file-size: 10MB

  mail:
    username: qyogapro@yandex.ru
    password: <secret>
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    resources:
      strategy:
        content:
          enabled=true
          paths=/**

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - https://www.googleapis.com/auth/calendar.events.readonly
              - email
            redirect-uri: "http://localhost:8080/therapist/oauth2/google/save-tokens"
            authorization-grant-type: authorization_code
            client-name: Trainer Advisor
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

management:
  endpoints:
    web:
      base-path: /ops/actuator

      exposure:
        include: configprops,loggers,env,info

  endpoint:
    configprops:
      show-values: when_authorized
      enabled: true
    env:
      enabled: true
      show-values: when_authorized

  info:
    git:
      mode: full
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

server:
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For

minio:
  user: user
  password: password
  endpoint: http://localhost:50000

trainer-advisor:
  admin:
    email: ta@azhidkov.pro

logging:
  level:
    org.springframework.security: DEBUG

debug: false