spring:
  flyway:
    out-of-order: true

  thymeleaf: # Thymeleaf
    cache: false
    prefix: file:app/src/main/resources/templates/
  web:
    resources:
      static-locations: file:app/src/main/resources/static/

  docker:
    compose:
      file: ./deploy/qyoga/docker-compose-infra-dev.yml
      enabled: true
      lifecycle-management: start_only

  mail:
    host: localhost
    port: 3025
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  health:
    mail:
      # При локальной разработке подключение к почтовому серверу не настроено
      enabled: false

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE