server:
  port: 10803

spring:
  mail:
    username: qyogapro@yandex.ru
    password: password
    host: localhost
    port: 10025
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:${server.port:8080}/therapist/oauth2/google/callback"
        provider:
          google:
            token-uri: http://localhost:8089/google/oauth/token
            user-info-uri: http://localhost:8089/google/oauth/userinfo

trainer-advisor:

  integrations:
    google-calendar:
      root-url: http://localhost:8089/google/