### Логин терапевтом
POST http://localhost:8080/login
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Content-Type: application/x-www-form-urlencoded

username = therapist%40trainer-advisor.pro &
password = password

###

### Произвольный корневой эндпоинт без аутентификации
// @no-cookie-jar
# @no-redirect
POST http://localhost:8080/it-isnt-opened
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
