POST http://localhost:8080/surveys
Content-Type: application/json

{
  "yandexAdminEmail": "therapist@trainer-advisor.pro",
  "surveyName": "Анкета",
  "survey": {
    "id": 1982681503,
    "survey_id": "67a325dde010db097c1208dc",
    "created": "2025-02-16T04:37:12Z",
    "lang": "ru",
    "answer": {
      "id": 1982681503,
      "uid": "202065830",
      "data": {
        "lastName": {
          "value": "Романов",
          "question": {
            "id": 69944398,
            "slug": "lastName",
            "options": {
              "required": true
            },
            "answer_type": {
              "id": 1,
              "slug": "answer_short_text"
            }
          }
        },
        "firstName": {
          "value": "Терек",
          "question": {
            "id": 69944599,
            "slug": "firstName",
            "options": {
              "required": true
            },
            "answer_type": {
              "id": 1,
              "slug": "answer_short_text"
            }
          }
        },
        "middleName": {
          "value": "Игоревич",
          "question": {
            "id": 69944672,
            "slug": "middleName",
            "options": {
              "required": false
            },
            "answer_type": {
              "id": 1,
              "slug": "answer_short_text"
            }
          }
        },
        "birthDate": {
          "value": "1988-02-01",
          "question": {
            "id": 69944723,
            "slug": "birthDate",
            "options": {
              "required": true,
              "date_range": false
            },
            "answer_type": {
              "id": 39,
              "slug": "answer_date"
            }
          }
        },
        "phoneNumber": {
          "value": "+7 999 222-33-46",
          "question": {
            "id": 69944855,
            "slug": "phoneNumber",
            "options": {
              "required": true
            },
            "answer_type": {
              "id": 38,
              "slug": "answer_phone"
            }
          }
        },
        "location": {
          "value": [
            {
              "key": "11786",
              "slug": "114917",
              "text": "Кавасаки, Префектура Канагава, Япония"
            }
          ],
          "question": {
            "id": 69944784,
            "slug": "location",
            "options": {
              "multiple": false,
              "required": false,
              "data_source": "city"
            },
            "answer_type": {
              "id": 3,
              "slug": "answer_choices"
            }
          }
        },
        "answer_short_text_69945487": {
          "value": "191",
          "question": {
            "id": 69945487,
            "slug": "answer_short_text_69945487",
            "options": {
              "required": false
            },
            "answer_type": {
              "id": 1,
              "slug": "answer_short_text"
            }
          }
        },
        "answer_short_text_69945577": {
          "value": "91",
          "question": {
            "id": 69945577,
            "slug": "answer_short_text_69945577",
            "options": {
              "required": false
            },
            "answer_type": {
              "id": 1,
              "slug": "answer_short_text"
            }
          }
        },
        "complaints": {
          "value": "В последнее время я испытываю сильные боли в пояснице, особенно после длительного сидения.\n\nЧасто чуствую онемение и покалывание в ногах, что мешает мне нормально ходить и работать.\n\nТакже беспокоит общее чувство усталости и слабости, которое не проходит после отдыха. Хотелось бы улучшить гибкость и снять напряжение с мышц, чтобы повысить качество жизни и вернуться к активному образу жизни",
          "question": {
            "id": 69945787,
            "slug": "complaints",
            "options": {
              "required": true
            },
            "answer_type": {
              "id": 2,
              "slug": "answer_long_text"
            }
          }
        },
        "answer_long_text_69945830": {
          "value": "В 2020 году я неудачно упал во время катания на велоспеде и сломал запястьте.\n\nЭто случилось в июле, и потребовался гипс на несколько недель.\n\nСейчас запястье полностью зажило, но иногда я чуствую небольшую боль при нагрузке.",
          "question": {
            "id": 69945830,
            "slug": "answer_long_text_69945830",
            "options": {
              "required": true
            },
            "answer_type": {
              "id": 2,
              "slug": "answer_long_text"
            }
          }
        },
        "answer_long_text_69946064": {
          "value": "Я обычно ложусь спать около 23:00. Заснуть мне удаётся довольно быстро, обычно в течении 15-20 минут. Ночью я редко просыпаюсь, максимум один раз. Если проснуться ночью, то засыпаю снова почти сразу. Просыпаюсь в 7:00 утра и чуствую себя бодрым и отдохнувшим, с хорошим настроением на весь день.",
          "question": {
            "id": 69946064,
            "slug": "answer_long_text_69946064",
            "options": {
              "required": true
            },
            "answer_type": {
              "id": 2,
              "slug": "answer_long_text"
            }
          }
        },
        "answer_long_text_69946477": {
          "value": "Да, я принимаю антигистаминные препараты на постоянной основе с начала весны, так как страдаю от сезонной аллергии. Начал их принимать около двух лет назад по рекомендации врача. Сейчас принимаю таблетки, содержащие лоратадин, для облегчения симпотом рефлексии.",
          "question": {
            "id": 69946477,
            "slug": "answer_long_text_69946477",
            "options": {
              "required": true
            },
            "answer_type": {
              "id": 2,
              "slug": "answer_long_text"
            }
          }
        }
      },
      "survey": {
        "id": "67a325dde010db097c1208dc"
      },
      "created": "2025-02-16T04:37:12Z"
    }
  },
  "questionNames": {
    "Фамилия": "Романов",
    "Имя": "Терек",
    "Отчество": "Игоревич",
    "Дата рождения": "1988-02-01",
    "Телефон для связи": "+7 999 222-33-44",
    "Город проживания": "Кавасаки, Префектура Канагава, Япония",
    "Ваш рост в см": "191",
    "Ваш вес": "91",
    "Жалобы": "В последнее время я испытываю сильные боли в пояснице, особенно после длительного сидения.\n\nЧасто чуствую онемение и покалывание в ногах, что мешает мне нормально ходить и работать.\n\nТакже беспокоит общее чувство усталости и слабости, которое не проходит после отдыха. Хотелось бы улучшить гибкость и снять напряжение с мышц, чтобы повысить качество жизни и вернуться к активному образу жизни",
    "Были ли травмы (примерная дата, характер травмы)": "В 2020 году я неудачно упал во время катания на велоспеде и сломал запястьте.\n\nЭто случилось в июле, и потребовался гипс на несколько недель.\n\nСейчас запястье полностью зажило, но иногда я чуствую небольшую боль при нагрузке.",
    "Опишите качество сна: во сколько ложитесь, легко ли засыпаете, просыпаетесь ли ночью, легко ли засыпаете, если проснулись ночью, как просыпаетесь, во сколько, какое самочувствие с утра": "Я обычно ложусь спать около 23:00. Заснуть мне удаётся довольно быстро, обычно в течении 15-20 минут. Ночью я редко просыпаюсь, максимум один раз. Если проснуться ночью, то засыпаю снова почти сразу. Просыпаюсь в 7:00 утра и чуствую себя бодрым и отдохнувшим, с хорошим настроением на весь день.",
    "Принимаете ли какие-то медикаменты на постоянной основе? Если да, то какие и как давно?": "Да, я принимаю антигистаминные препараты на постоянной основе с начала весны, так как страдаю от сезонной аллергии. Начал их принимать около двух лет назад по рекомендации врача. Сейчас принимаю таблетки, содержащие лоратадин, для облегчения симпотом рефлексии."
  }
}