style:
  UnusedImport:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateFunction:
    active: true
  UnusedPrivateProperty:
    active: true

complexity:
  CognitiveComplexMethod:
    active: true
    allowedComplexity: 15
